apiVersion: 1
datasources:
	- name: Loki
		type: loki
		access: proxy
		url: http://loki:3100
		isDefault: true
		jsonData:
			derivedFields:
				- name: traceID
					matcherRegex: "trace_id=(\\w+)"
					datasourceUid: tempo
					url: '$${__value.raw}'
	- name: Tempo
		uid: tempo
		type: tempo
		access: proxy
		url: http://tempo:3200
		jsonData:
			httpMethod: GET
			tracesToLogs:
				datasourceUid: Loki
				tags: ["service.name","deployment.environment","region"]
				spanStartTimeShift: "-5m"
				spanEndTimeShift: "5m"
				filterByTraceID: true
				filterBySpanID: false
			serviceMap:
				datasourceUid: Loki
			nodeGraph:
				enabled: true
	- name: Mimir
		type: prometheus
		access: proxy
		url: http://mimir:9009
		isDefault: false
		jsonData:
			httpMethod: GET
			exemplarTraceIdDestinations:
				- name: traceID
					datasourceUid: tempo
