
server:
	http_listen_port: 3200

distributor:
	receivers:
		otlp:
			protocols:
				grpc: {}
				http: {}

ingester:
	trace_idle_period: 10s
	max_block_bytes: 1048576
	max_block_duration: 5m

compactor:
	compaction:
		block_retention: 24h

metrics_generator:
	registry:
		external_labels:
			source: tempo
	storage:
		path: /tmp/tempo/generator
	processor:
		service_graphs: {}
		span_metrics: {}

storage:
	trace:
		backend: local
		local:
			path: /tmp/tempo/traces

overrides:
	metrics_generator_processors: [service-graphs, span-metrics]
